//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya20
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заключение договора.
    /// </summary>
    // *** Start programmer edit section *** (Договор CustomAttributes)

    // *** End programmer edit section *** (Договор CustomAttributes)
    [AutoAltered()]
    [Caption("Заключение договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДоговорE", new string[] {
            "Стоимость as \'Стоимость\'",
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Длительность as \'Длительность\'",
            "Статус as \'Статус\'",
            "ДирОтдПоРабСКл",
            "ДирОтдПоРабСКл.Фамилия",
            "ДирОтдПоРабСКл.Имя",
            "ДирОтдПоРабСКл.Отчество",
            "Клиент",
            "Клиент.Фамилия",
            "Клиент.Имя",
            "Клиент.Отчество"})]
    [View("ДоговорL", new string[] {
            "Стоимость as \'Стоимость\'",
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Длительность as \'Длительность\'",
            "Статус as \'Статус\'",
            "ДирОтдПоРабСКл",
            "ДирОтдПоРабСКл.Фамилия",
            "ДирОтдПоРабСКл.Имя",
            "ДирОтдПоРабСКл.Отчество",
            "Клиент",
            "Клиент.Фамилия",
            "Клиент.Имя",
            "Клиент.Отчество"})]
    [View("ЗаключДоговораE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Длительность",
            "Стоимость as \'Стоимость\'"})]
    [View("ЗаключДоговораL", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Длительность",
            "Стоимость as \'Стоимость\'"})]
    public class Договор : ICSSoft.STORMNET.DataObject
    {
        
        private int fСтоимость;
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Kursovaya20.ТипДоговора fТип;
        
        private int fДлительность;
        
        private IIS.Kursovaya20.Статус fСтатус;
        
        private IIS.Kursovaya20.Клиент fКлиент;
        
        private IIS.Kursovaya20.ДирОтдПоРабСКл fДирОтдПоРабСКл;
        
        // *** Start programmer edit section *** (Договор CustomMembers)

        // *** End programmer edit section *** (Договор CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Дата CustomAttributes)

        // *** End programmer edit section *** (Договор.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Дата Get start)

                // *** End programmer edit section *** (Договор.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Договор.Дата Get end)

                // *** End programmer edit section *** (Договор.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Дата Set start)

                // *** End programmer edit section *** (Договор.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Договор.Дата Set end)

                // *** End programmer edit section *** (Договор.Дата Set end)
            }
        }
        
        /// <summary>
        /// Длительность.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Длительность CustomAttributes)

        // *** End programmer edit section *** (Договор.Длительность CustomAttributes)
        public virtual int Длительность
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Длительность Get start)

                // *** End programmer edit section *** (Договор.Длительность Get start)
                int result = this.fДлительность;
                // *** Start programmer edit section *** (Договор.Длительность Get end)

                // *** End programmer edit section *** (Договор.Длительность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Длительность Set start)

                // *** End programmer edit section *** (Договор.Длительность Set start)
                this.fДлительность = value;
                // *** Start programmer edit section *** (Договор.Длительность Set end)

                // *** End programmer edit section *** (Договор.Длительность Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Номер CustomAttributes)

        // *** End programmer edit section *** (Договор.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Номер Get start)

                // *** End programmer edit section *** (Договор.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Договор.Номер Get end)

                // *** End programmer edit section *** (Договор.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Номер Set start)

                // *** End programmer edit section *** (Договор.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Договор.Номер Set end)

                // *** End programmer edit section *** (Договор.Номер Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Статус CustomAttributes)

        // *** End programmer edit section *** (Договор.Статус CustomAttributes)
        public virtual IIS.Kursovaya20.Статус Статус
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Статус Get start)

                // *** End programmer edit section *** (Договор.Статус Get start)
                IIS.Kursovaya20.Статус result = this.fСтатус;
                // *** Start programmer edit section *** (Договор.Статус Get end)

                // *** End programmer edit section *** (Договор.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Статус Set start)

                // *** End programmer edit section *** (Договор.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Договор.Статус Set end)

                // *** End programmer edit section *** (Договор.Статус Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Стоимость CustomAttributes)

        // *** End programmer edit section *** (Договор.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Стоимость Get start)

                // *** End programmer edit section *** (Договор.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (Договор.Стоимость Get end)

                // *** End programmer edit section *** (Договор.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Стоимость Set start)

                // *** End programmer edit section *** (Договор.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (Договор.Стоимость Set end)

                // *** End programmer edit section *** (Договор.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Тип CustomAttributes)

        // *** End programmer edit section *** (Договор.Тип CustomAttributes)
        public virtual IIS.Kursovaya20.ТипДоговора Тип
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Тип Get start)

                // *** End programmer edit section *** (Договор.Тип Get start)
                IIS.Kursovaya20.ТипДоговора result = this.fТип;
                // *** Start programmer edit section *** (Договор.Тип Get end)

                // *** End programmer edit section *** (Договор.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Тип Set start)

                // *** End programmer edit section *** (Договор.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (Договор.Тип Set end)

                // *** End programmer edit section *** (Договор.Тип Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (Договор.ДирОтдПоРабСКл CustomAttributes)

        // *** End programmer edit section *** (Договор.ДирОтдПоРабСКл CustomAttributes)
        [PropertyStorage(new string[] {
                "ДирОтдПоРабСКл"})]
        [NotNull()]
        public virtual IIS.Kursovaya20.ДирОтдПоРабСКл ДирОтдПоРабСКл
        {
            get
            {
                // *** Start programmer edit section *** (Договор.ДирОтдПоРабСКл Get start)

                // *** End programmer edit section *** (Договор.ДирОтдПоРабСКл Get start)
                IIS.Kursovaya20.ДирОтдПоРабСКл result = this.fДирОтдПоРабСКл;
                // *** Start programmer edit section *** (Договор.ДирОтдПоРабСКл Get end)

                // *** End programmer edit section *** (Договор.ДирОтдПоРабСКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.ДирОтдПоРабСКл Set start)

                // *** End programmer edit section *** (Договор.ДирОтдПоРабСКл Set start)
                this.fДирОтдПоРабСКл = value;
                // *** Start programmer edit section *** (Договор.ДирОтдПоРабСКл Set end)

                // *** End programmer edit section *** (Договор.ДирОтдПоРабСКл Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (Договор.Клиент CustomAttributes)

        // *** End programmer edit section *** (Договор.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Kursovaya20.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (Договор.Клиент Get start)

                // *** End programmer edit section *** (Договор.Клиент Get start)
                IIS.Kursovaya20.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (Договор.Клиент Get end)

                // *** End programmer edit section *** (Договор.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Договор.Клиент Set start)

                // *** End programmer edit section *** (Договор.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (Договор.Клиент Set end)

                // *** End programmer edit section *** (Договор.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДоговорE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорE", typeof(IIS.Kursovaya20.Договор));
                }
            }
            
            /// <summary>
            /// "ДоговорL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДоговорL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДоговорL", typeof(IIS.Kursovaya20.Договор));
                }
            }
            
            /// <summary>
            /// "ЗаключДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаключДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаключДоговораE", typeof(IIS.Kursovaya20.Договор));
                }
            }
            
            /// <summary>
            /// "ЗаключДоговораL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаключДоговораL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаключДоговораL", typeof(IIS.Kursovaya20.Договор));
                }
            }
        }
    }
}
