//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya20
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет оставшегося времени.
    /// </summary>
    // *** Start programmer edit section *** (РасчетОстВрем CustomAttributes)

    // *** End programmer edit section *** (РасчетОстВрем CustomAttributes)
    [AutoAltered()]
    [Caption("Расчет оставшегося времени")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетОстВремE", new string[] {
            "Было",
            "Доступно",
            "Использовано"})]
    [AssociatedDetailViewAttribute("РасчетОстВремE", "ОказКонсулт", "ОказКонсультE", false, "", "", true, new string[] {
            ""})]
    [View("РасчетОстВремL", new string[] {
            "Было",
            "Доступно",
            "Использовано"})]
    public class РасчетОстВрем : ICSSoft.STORMNET.DataObject
    {
        
        private int fБыло;
        
        private int fИспользовано;
        
        private int fДоступно;
        
        private IIS.Kursovaya20.DetailArrayOfОказКонсульт fОказКонсулт;
        
        // *** Start programmer edit section *** (РасчетОстВрем CustomMembers)

        // *** End programmer edit section *** (РасчетОстВрем CustomMembers)

        
        /// <summary>
        /// Было.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Было CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Было CustomAttributes)
        public virtual int Было
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Было Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Было Get start)
                int result = this.fБыло;
                // *** Start programmer edit section *** (РасчетОстВрем.Было Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Было Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Было Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Было Set start)
                this.fБыло = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Было Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Было Set end)
            }
        }
        
        /// <summary>
        /// Доступно.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)
        public virtual int Доступно
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get start)
                int result = this.fДоступно;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set start)
                this.fДоступно = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set end)
            }
        }
        
        /// <summary>
        /// Использовано.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)
        public virtual int Использовано
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get start)
                int result = this.fИспользовано;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set start)
                this.fИспользовано = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set end)
            }
        }
        
        /// <summary>
        /// Расчет оставшегося времени.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсулт CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.ОказКонсулт CustomAttributes)
        public virtual IIS.Kursovaya20.DetailArrayOfОказКонсульт ОказКонсулт
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсулт Get start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсулт Get start)
                if ((this.fОказКонсулт == null))
                {
                    this.fОказКонсулт = new IIS.Kursovaya20.DetailArrayOfОказКонсульт(this);
                }
                IIS.Kursovaya20.DetailArrayOfОказКонсульт result = this.fОказКонсулт;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсулт Get end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсулт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсулт Set start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсулт Set start)
                this.fОказКонсулт = value;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказКонсулт Set end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказКонсулт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетОстВремE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетОстВремE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетОстВремE", typeof(IIS.Kursovaya20.РасчетОстВрем));
                }
            }
            
            /// <summary>
            /// "РасчетОстВремL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетОстВремL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетОстВремL", typeof(IIS.Kursovaya20.РасчетОстВрем));
                }
            }
        }
    }
}
